spring:
  datasource:
    url: ${spring_datasource_url:jdbc:postgresql://postgres:5432/core-service-db}
    username: ${spring_datasource_username:postgres}
    password: ${spring_datasource_password:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${spring_jpa_hibernate_ddl-auto:update}
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

app:
  security:
    jwt-token:
      permit-all:
        - /api/bank-accounts/token
      root-path: /api
      secret: qqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrttty
      issuer: online-bank-api
      subject: User details
    integrations:
      root-path: /integration
      api-key: ac816388c1c44ac2b2ae431f89c82e7e345d25a0e6474e75a78f9a5ce496060c

integration:
  request:
    check-user-existence: http://host.docker.internal:7788/user_api/user/{userId}/exist